/*


From here on is not Fractyl's creation and is the hack script code.


*/
const _lastKnownHash = `CiAgCi8qCiAgRWxlbWVudGFsIGNsb25lLCBkZXZlbG9wbWVudCBiZWdhbiAxNSBPY3RvYmVyIDIwMjQKICBJbnNwaXJlZCBieSBDYXJ5IEh1YW5nJ3MgRWxlbWVudGFsIGdhbWVzLCBPcnRlaWwncyBHZW5lc2lzLCBhbmQgc2ltaWxhciBnYW1lcwogIElmIHlvdSdyZSBqdXN0IGxvb2tpbmcgZm9yIGFsbCB0aGUgZWxlbWVudHMgYW5kIGNvbWJpbmF0aW9ucywgdGhleSdyZSBhbGwgaGVyZToKCiAgICAgICAgICBodHRwczovL2ZyYWN0eWwubmVvY2l0aWVzLm9yZy9leHBlcmltZW50cy9lbGVtZW50YWwvZGF0YS50eHQKCiovCgp2YXIgZCA9IHsKICBnaWQ6ZnVuY3Rpb24oaWQpe3JldHVybiBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChpZCl9LAogIGd0bjpmdW5jdGlvbih0bil7cmV0dXJuIGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKHRuKX0sCiAgZ2NuOmZ1bmN0aW9uKGNuKXtyZXR1cm4gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShjbil9LAogIGNlOmZ1bmN0aW9uKHRhZyl7cmV0dXJuIGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQodGFnKX0sCiAgcXM6ZnVuY3Rpb24ocXJ5KXtyZXR1cm4gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihxcnkpfQp9Cgp2YXIgZWxlbWVudHNCb3ggPSBkLmdpZCgnZWxlbWVudHMnKTsKdmFyIGJhc2ljRWxlbWVudHNCb3ggPSBkLmdpZCgnYmFzaWNfZWxlbWVudHMnKTsKdmFyIGZpbmFsRWxlbWVudHNCb3ggPSBkLmdpZCgnZmluYWxfZWxlbWVudHMnKTsKdmFyIHNlbGVjdGVkRGlzcGxheSA9IGQuZ2lkKCdzZWxlY3RlZCcpOwp2YXIgcmVzdWx0RGlzcGxheSA9IGQuZ2lkKCdyZXN1bHQnKTsKdmFyIGVsZW1lbnRzRGlzcGxheSA9IGQuZ2lkKCdlbGVtZW50X2NvdW50ZXInKTsKCnZhciBiYXNpY0VsZW1lbnRzID0gWydhaXInLCdlYXJ0aCcsJ2ZpcmUnLCd3YXRlciddOwp2YXIgY2F0ZWdvcmllcyA9IHt9Owp2YXIgZWxlbWVudHMgPSB7fTsKdmFyIGZvcm11bGFlID0gW107CnZhciBzZWxlY3RlZEVsZW1lbnRzID0gWycnLCcnXTsKCmZ1bmN0aW9uIGZldGNoRGF0YSgpIHsKICBmZXRjaChgLi9kYXRhLnR4dGApLnRoZW4oZGF0YSA9PiBkYXRhLnRleHQoKSkudGhlbih0ZXh0ID0+IHsKICAgIHRleHQgPSB0ZXh0LnNwbGl0KCcqKkNBVEVHT1JJRVMqKlxyXG4nKVsxXQogICAgbGV0IGZldGNoZWRDYXRlZ29yaWVzID0gdGV4dC5zcGxpdCgnXHJcbioqRUxFTUVOVFMqKlxyXG4nKVswXQogICAgdGV4dCA9IHRleHQuc3BsaXQoJ1xyXG4qKkVMRU1FTlRTKipcclxuJylbMV0KICAgIGxldCBmZXRjaGVkRWxlbWVudHMgPSB0ZXh0LnNwbGl0KCdcclxuKipGT1JNVUxBRSoqXHJcbicpWzBdCiAgICBsZXQgZmV0Y2hlZEZvcm11bGFlID0gdGV4dC5zcGxpdCgnXHJcbioqRk9STVVMQUUqKlxyXG4nKVsxXQogICAgZmV0Y2hlZENhdGVnb3JpZXMuc3BsaXQoJ1xyXG4nKS5mb3JFYWNoKGNhdGVnb3J5ID0+IHsKICAgICAgaWYgKGNhdGVnb3J5ICE9ICcnKSB7CiAgICAgICAgY2F0ZWdvcmllc1tjYXRlZ29yeS5zcGxpdCgnfCcpWzBdLnRyaW0oKV0gPSB7Y29sb3I6Y2F0ZWdvcnkuc3BsaXQoJ3wnKVsxXS50cmltKCl9CiAgICAgIH0KICAgIH0pCiAgICBmZXRjaGVkRWxlbWVudHMuc3BsaXQoJ1xyXG4nKS5mb3JFYWNoKGVsZW1lbnQgPT4gewogICAgICBpZiAoZWxlbWVudCAhPSAnJykgewogICAgICAgIGVsZW1lbnRzW2VsZW1lbnQuc3BsaXQoJ3wnKVswXS50cmltKCldID0gewogICAgICAgICAgY2F0ZWdvcnk6ZWxlbWVudC5zcGxpdCgnfCcpWzFdLnRyaW0oKSwKICAgICAgICAgIG93bmVkOmJhc2ljRWxlbWVudHMuaW5jbHVkZXMoZWxlbWVudC5zcGxpdCgnfCcpWzBdLnRyaW0oKSksCiAgICAgICAgICBzZWxlY3RlZDpmYWxzZQogICAgICAgIH0KICAgICAgfQogICAgfSkKICAgIGZldGNoZWRGb3JtdWxhZS5zcGxpdCgnXHJcbicpLmZvckVhY2goZm9ybXVsYSA9PiB7CiAgICAgIGlmIChmb3JtdWxhICE9ICcnKSB7CiAgICAgICAgbGV0IGNvbXBvbmVudHMgPSBmb3JtdWxhLnNwbGl0KCc9JylbMF0KICAgICAgICBsZXQgcHJvZHVjdHMgPSBmb3JtdWxhLnNwbGl0KCc9JylbMV0KICAgICAgICBmb3JtdWxhZS5wdXNoKHsKICAgICAgICAgIGVsZW1lbnRzOmNvbXBvbmVudHMuc3BsaXQoJysnKS5tYXAoZWxlbSA9PiBlbGVtLnRyaW0oKSksCiAgICAgICAgICBwcm9kdWN0czpwcm9kdWN0cy5zcGxpdCgnKycpLm1hcChwID0+IHAudHJpbSgpKSwKICAgICAgICB9KQogICAgICB9CiAgICB9KQogICAgc29ydEVsZW1lbnRzKCkKICAgIGxvYWQoKQogICAgdXBkYXRlU2VsZWN0ZWREaXNwbGF5KCkKICB9KQp9CgpBcnJheS5wcm90b3R5cGUucmVtb3ZlID0gZnVuY3Rpb24odmFsKSB7CiAgbGV0IGkgPSB0aGlzLmluZGV4T2YodmFsKTsKICBpZiAoaT4tMSkge3RoaXMuc3BsaWNlKGksIDEpO30KICByZXR1cm4gdGhpczsKfQoKZnVuY3Rpb24gc29ydEVsZW1lbnRzKCkgewogIGxldCBrZXlhcnIgPSBiYXNpY0VsZW1lbnRzLmNvbmNhdChPYmplY3Qua2V5cyhlbGVtZW50cykuc29ydCgpLnJlbW92ZSgnYWlyJykucmVtb3ZlKCd3YXRlcicpLnJlbW92ZSgnZmlyZScpLnJlbW92ZSgnZWFydGgnKSkKICBsZXQgb2xkZWxlbWVudHMgPSBlbGVtZW50czsKICBlbGVtZW50cyA9IHt9OwogIGtleWFyci5mb3JFYWNoKGtleSA9PiB7CiAgICBlbGVtZW50c1trZXldID0gb2xkZWxlbWVudHNba2V5XQogIH0pCn0KCmZ1bmN0aW9uIHVwZGF0ZUVsZW1lbnRzKCkgewogIGVsZW1lbnRzQm94LmlubmVySFRNTCA9ICIiCiAgYmFzaWNFbGVtZW50c0JveC5pbm5lckhUTUwgPSAiIgogIGZpbmFsRWxlbWVudHNCb3guaW5uZXJIVE1MID0gIiIKICB2YXIgZWxlbVByZXNlbmNlID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShlbGVtZW50cykpCiAgT2JqZWN0LmtleXMoZWxlbVByZXNlbmNlKS5mb3JFYWNoKGtleSA9PiB7ZWxlbVByZXNlbmNlW2tleV0gPSAwfSkKICBPYmplY3Qua2V5cyhmb3JtdWxhZSkuZm9yRWFjaChrZXkgPT4gewogICAgbGV0IGZvcm11bGEgPSBmb3JtdWxhZVtrZXldCiAgICBlbGVtUHJlc2VuY2VbZm9ybXVsYS5lbGVtZW50c1swXV0rKwogICAgaWYgKGZvcm11bGEuZWxlbWVudHNbMF0gIT0gZm9ybXVsYS5lbGVtZW50c1sxXSkge2VsZW1QcmVzZW5jZVtmb3JtdWxhLmVsZW1lbnRzWzFdXSsrfQogIH0pCiAgT2JqZWN0LmtleXMoZWxlbWVudHMpLmZvckVhY2goa2V5ID0+IHsKICAgIGxldCBlbGVtZW50ID0gZWxlbWVudHNba2V5XQogICAgaWYgKGVsZW1lbnQub3duZWQpIHsKICAgICAgbGV0IGVsZW1EaXYgPSBkLmNlKCdkaXYnKQogICAgICBlbGVtRGl2LmNsYXNzTGlzdC5hZGQoJ2VsZW1lbnQnKQogICAgICBpZiAoZWxlbWVudC5zZWxlY3RlZCkge2VsZW1EaXYuY2xhc3NMaXN0LmFkZCgnc2VsZWN0ZWQnKX0KICAgICAgZWxlbURpdi5pbm5lckhUTUwgPSBrZXkKICAgICAgZWxlbURpdi5zdHlsZSA9IGBiYWNrZ3JvdW5kLWNvbG9yOiR7Y2F0ZWdvcmllc1tlbGVtZW50LmNhdGVnb3J5XS5jb2xvcn07IGNvbG9yOiR7Y29udHJhc3RDb2xvcihjYXRlZ29yaWVzW2VsZW1lbnQuY2F0ZWdvcnldLmNvbG9yKX07YAogICAgICBlbGVtRGl2LmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywoKSA9PiB7CiAgICAgICAgc2VsZWN0RWxlbWVudChrZXkpCiAgICAgIH0pCiAgICAgIGlmIChiYXNpY0VsZW1lbnRzLmluY2x1ZGVzKGtleSkpIHtiYXNpY0VsZW1lbnRzQm94LmFwcGVuZENoaWxkKGVsZW1EaXYpfQogICAgICBlbHNlIHsKICAgICAgICBpZiAoZWxlbVByZXNlbmNlW2tleV0gPT0gMCkgewogICAgICAgICAgaWYgKGQuZ2lkKCdzZWFyY2hfaW5wdXQnKS52YWx1ZSAhPSAnJykgewogICAgICAgICAgICBpZiAoa2V5LnRvVXBwZXJDYXNlKCkuaW5kZXhPZihkLmdpZCgnc2VhcmNoX2lucHV0JykudmFsdWUudG9VcHBlckNhc2UoKSkgPiAtMSkge2ZpbmFsRWxlbWVudHNCb3guYXBwZW5kQ2hpbGQoZWxlbURpdil9CiAgICAgICAgICB9IGVsc2Uge2ZpbmFsRWxlbWVudHNCb3guYXBwZW5kQ2hpbGQoZWxlbURpdil9CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgIGlmIChkLmdpZCgnc2VhcmNoX2lucHV0JykudmFsdWUgIT0gJycpIHsKICAgICAgICAgICAgaWYgKGtleS50b1VwcGVyQ2FzZSgpLmluZGV4T2YoZC5naWQoJ3NlYXJjaF9pbnB1dCcpLnZhbHVlLnRvVXBwZXJDYXNlKCkpID4gLTEpIHtlbGVtZW50c0JveC5hcHBlbmRDaGlsZChlbGVtRGl2KX0KICAgICAgICAgIH0gZWxzZSB7ZWxlbWVudHNCb3guYXBwZW5kQ2hpbGQoZWxlbURpdil9CiAgICAgICAgfQogICAgICB9CiAgICB9CiAgfSkKfQoKZnVuY3Rpb24gc2VhcmNoKCkge3VwZGF0ZUVsZW1lbnRzKCdzZWFyY2gnKX0KCnZhciBzdHlsZSA9IDAKdmFyIHN0eWxlcyA9IFsKICBgLmVsZW1lbnQgewogIHdpZHRoOjU0cHg7CiAgaGVpZ2h0OjU0cHg7CiB9YCwKYGAKXQpmdW5jdGlvbiBzd2l0Y2hTdHlsZSgpIHsKICBzdHlsZSA9IChzdHlsZSsxKSUyCiAgZG9jdW1lbnQuaGVhZC5nZXRFbGVtZW50c0J5VGFnTmFtZSgnc3R5bGUnKVswXS5pbm5lckhUTUwgPSBzdHlsZXNbc3R5bGVdCn0KCmZ1bmN0aW9uIGNvbnRyYXN0Q29sb3IoY2xyKSB7CiAgbGV0IGNvbG9yID0gY2xyLnNwbGl0KCcjJylbMV0uc3BsaXQoJycpLm1hcCh2ID0+IHBhcnNlSW50KHYrdiwgMTYpKQogIGlmICgoY29sb3JbMF0qMC4yOTkpICsgKGNvbG9yWzFdKjAuNTg3KSArIChjb2xvclsyXSowLjExNCkgPiAxODYpIHtyZXR1cm4gJyMwMDAnfSBlbHNlIHtyZXR1cm4gJyNmZmYnfQp9CgpmdW5jdGlvbiBsb2dTdGF0cygpIHsKICBjb25zb2xlLmxvZyhgVGhlcmUgYXJlICR7T2JqZWN0LmtleXMoZWxlbWVudHMpLmxlbmd0aH0gZWxlbWVudHMgYW5kICR7T2JqZWN0LmtleXMoZm9ybXVsYWUpLmxlbmd0aH0gZm9ybXVsYWUuYCkKICBsZXQgbG9uZ2VzdEtleXMgPSBbJ2EnXQogIGxldCBzaG9ydGVzdEtleXMgPSBbJ2FhYWFhYWFhYWFhYWFhYWEnXQogIGxldCBrZXlzQWxwaGFiZXQgPSBPYmplY3Qua2V5cyhlbGVtZW50cykuc29ydCgpCiAgT2JqZWN0LmtleXMoZWxlbWVudHMpLmZvckVhY2goa2V5ID0+IHsKICAgIGlmIChrZXkubGVuZ3RoID4gbG9uZ2VzdEtleXNbMF0ubGVuZ3RoKSB7bG9uZ2VzdEtleXMgPSBba2V5XX0KICAgIGVsc2UgaWYgKGtleS5sZW5ndGggPT0gbG9uZ2VzdEtleXNbMF0ubGVuZ3RoKSB7bG9uZ2VzdEtleXMucHVzaChrZXkpfQogICAgaWYgKGtleS5sZW5ndGggPCBzaG9ydGVzdEtleXNbMF0ubGVuZ3RoKSB7c2hvcnRlc3RLZXlzID0gW2tleV19CiAgICBlbHNlIGlmIChrZXkubGVuZ3RoID09IHNob3J0ZXN0S2V5c1swXS5sZW5ndGgpIHtzaG9ydGVzdEtleXMucHVzaChrZXkpfQogIH0pCiAgY29uc29sZS5sb2coYFRoZSBsb25nZXN0IGVsZW1lbnQocyk6ICR7bG9uZ2VzdEtleXMuam9pbignLCAnKX0gd2l0aCAke2xvbmdlc3RLZXlzWzBdLmxlbmd0aH0gY2hhcmFjdGVycy5gKQogIGNvbnNvbGUubG9nKGBUaGUgc2hvcnRlc3QgZWxlbWVudChzKTogJHtzaG9ydGVzdEtleXMuam9pbignLCAnKX0gd2l0aCAke3Nob3J0ZXN0S2V5c1swXS5sZW5ndGh9IGNoYXJhY3RlcnMuYCkKICBjb25zb2xlLmxvZyhgRmlyc3QgYWxwaGFiZXRpY2FsbHk6ICR7a2V5c0FscGhhYmV0WzBdfSB8IExhc3QgYWxwaGFiZXRpY2FsbHk6ICR7a2V5c0FscGhhYmV0W2tleXNBbHBoYWJldC5sZW5ndGgtMV19YCkKICBsZXQgYmVzdEVsZW1lbnRzID0gWydyYWluJ10KICBsZXQgYmVzdFByb2R1Y3RzID0gWydyYWluJ10KICBsZXQgZWxlbWVudFRyYWNraW5nID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShlbGVtZW50cykpCiAgbGV0IHByb2R1Y3RUcmFja2luZyA9IEpTT04ucGFyc2UoSlNPTi5zdHJpbmdpZnkoZWxlbWVudHMpKQogIE9iamVjdC5rZXlzKGVsZW1lbnRUcmFja2luZykuZm9yRWFjaChrZXkgPT4ge2VsZW1lbnRUcmFja2luZ1trZXldID0gMH0pCiAgT2JqZWN0LmtleXMocHJvZHVjdFRyYWNraW5nKS5mb3JFYWNoKGtleSA9PiB7cHJvZHVjdFRyYWNraW5nW2tleV0gPSAwfSkKICBPYmplY3Qua2V5cyhmb3JtdWxhZSkuZm9yRWFjaChrZXkgPT4gewogICAgbGV0IGZvcm11bGEgPSBmb3JtdWxhZVtrZXldCiAgICBlbGVtZW50VHJhY2tpbmdbZm9ybXVsYS5lbGVtZW50c1swXV0rKwogICAgaWYgKGZvcm11bGEuZWxlbWVudHNbMF0gIT0gZm9ybXVsYS5lbGVtZW50c1sxXSkge2VsZW1lbnRUcmFja2luZ1tmb3JtdWxhLmVsZW1lbnRzWzFdXSsrfQogICAgZm9ybXVsYS5wcm9kdWN0cy5mb3JFYWNoKChibGFoYmxhaCxpKSA9PiB7cHJvZHVjdFRyYWNraW5nW2Zvcm11bGEucHJvZHVjdHNbaV1dKys7fSkKICB9KQogIE9iamVjdC5rZXlzKGVsZW1lbnRUcmFja2luZykuZm9yRWFjaChrZXkgPT4gewogICAgaWYgKGVsZW1lbnRUcmFja2luZ1trZXldID4gZWxlbWVudFRyYWNraW5nW2Jlc3RFbGVtZW50c1swXV0pIHtiZXN0RWxlbWVudHMgPSBba2V5XX0KICAgIGVsc2UgaWYgKGVsZW1lbnRUcmFja2luZ1trZXldID09IGVsZW1lbnRUcmFja2luZ1tiZXN0RWxlbWVudHNbMF1dKSB7YmVzdEVsZW1lbnRzLnB1c2goa2V5KX0KICB9KQogIE9iamVjdC5rZXlzKHByb2R1Y3RUcmFja2luZykuZm9yRWFjaChrZXkgPT4gewogICAgaWYgKHByb2R1Y3RUcmFja2luZ1trZXldID4gcHJvZHVjdFRyYWNraW5nW2Jlc3RQcm9kdWN0c1swXV0pIHtiZXN0UHJvZHVjdHMgPSBba2V5XX0KICAgIGVsc2UgaWYgKHByb2R1Y3RUcmFja2luZ1trZXldID09IHByb2R1Y3RUcmFja2luZ1tiZXN0UHJvZHVjdHNbMF1dKSB7YmVzdFByb2R1Y3RzLnB1c2goa2V5KX0KICB9KQogIGNvbnNvbGUubG9nKGBCZXN0IGVsZW1lbnQocyk6ICR7YmVzdEVsZW1lbnRzLmpvaW4oJywgJyl9IHVzZWQgaW4gJHtlbGVtZW50VHJhY2tpbmdbYmVzdEVsZW1lbnRzWzBdXX0gZm9ybXVsYWVgKQogIGNvbnNvbGUubG9nKGBCZXN0IHByb2R1Y3Qocyk6ICR7YmVzdFByb2R1Y3RzLmpvaW4oJywgJyl9IG1hZGUgd2l0aCAke3Byb2R1Y3RUcmFja2luZ1tiZXN0UHJvZHVjdHNbMF1dfSBmb3JtdWxhZWApCn0KCmZ1bmN0aW9uIGZpbmRQcm9kdWN0cyhlbGVtMSxlbGVtMikgewogIGxldCBmb3VuZEZvcm11bGEgPSBmb3JtdWxhZS5maW5kKGZvcm11bGEgPT4gewogICAgbGV0IGVsZW1zMSA9IFtlbGVtMSxlbGVtMl0uc29ydCgpCiAgICBsZXQgZWxlbXMyID0gZm9ybXVsYS5lbGVtZW50cy5zb3J0KCkKICAgIGZvciAobGV0IGkgPSAwOyBpIDwgMjsgaSsrKSB7aWYgKGVsZW1zMVtpXSAhPT0gZWxlbXMyW2ldKSB7cmV0dXJuIGZhbHNlO319CiAgICByZXR1cm4gdHJ1ZTsKICB9KQogIHJldHVybiB0eXBlb2YgZm91bmRGb3JtdWxhID09ICd1bmRlZmluZWQnP3VuZGVmaW5lZDpmb3VuZEZvcm11bGEucHJvZHVjdHM7Cn0KCmZ1bmN0aW9uIHNlbGVjdEVsZW1lbnQoa2V5KSB7CiAgaWYgKHNlbGVjdGVkRWxlbWVudHMuaW5kZXhPZigiIikgPT0gLTEpIHsKICAgIGVsZW1lbnRzW2tleV0uc2VsZWN0ZWQgPSB0cnVlOwogICAgZWxlbWVudHNbc2VsZWN0ZWRFbGVtZW50c1swXV0uc2VsZWN0ZWQgPSBzZWxlY3RlZEVsZW1lbnRzWzBdID09IHNlbGVjdGVkRWxlbWVudHNbMV0gLy8gdGhlIG9sZCBzZWxlY3RlZCBlbGVtZW50IHN0YXlzIHNlbGVjdGVkIGlmIGl0IHdhcyBpbiBib3RoIHNsb3RzCiAgICBzZWxlY3RlZEVsZW1lbnRzWzBdID0gc2VsZWN0ZWRFbGVtZW50c1sxXQogICAgc2VsZWN0ZWRFbGVtZW50c1sxXSA9IGtleQogIH0KICBlbHNlIHsKICAgIGlmIChzZWxlY3RlZEVsZW1lbnRzWzBdID09ICIiKSB7c2VsZWN0ZWRFbGVtZW50c1swXSA9IGtleX0KICAgIGVsc2Uge3NlbGVjdGVkRWxlbWVudHNbMV0gPSBrZXl9CiAgICBlbGVtZW50c1trZXldLnNlbGVjdGVkID0gdHJ1ZTsKICB9CiAgdXBkYXRlU2VsZWN0ZWREaXNwbGF5KCkKICB1cGRhdGVFbGVtZW50cygpCn0KCmZ1bmN0aW9uIHVwZGF0ZVNlbGVjdGVkRGlzcGxheSgpIHsKICBzZWxlY3RlZERpc3BsYXkuaW5uZXJIVE1MID0gYCR7c2VsZWN0ZWRFbGVtZW50c1swXT09Jyc/J19fX19fJzpzZWxlY3RlZEVsZW1lbnRzWzBdfSArICR7c2VsZWN0ZWRFbGVtZW50c1sxXT09Jyc/J19fX19fJzpzZWxlY3RlZEVsZW1lbnRzWzFdfWAKfQoKZnVuY3Rpb24gdXBkYXRlRWxlbWVudHNEaXNwbGF5KCkgewogIGxldCBlbGVtc08gPSAwCiAgT2JqZWN0LmtleXMoZWxlbWVudHMpLmZvckVhY2goa2V5ID0+IHtpZiAoZWxlbWVudHNba2V5XS5vd25lZCkge2VsZW1zTysrfX0pCiAgZWxlbWVudHNEaXNwbGF5LmlubmVySFRNTCA9IGAke2VsZW1zT30vJHtPYmplY3Qua2V5cyhlbGVtZW50cykubGVuZ3RofWAKfQoKZnVuY3Rpb24gY29tYmluZUVsZW1lbnRzKCkgewogIGlmIChzZWxlY3RlZEVsZW1lbnRzLmluZGV4T2YoIiIpID09IC0xKSB7CiAgICBsZXQgcHJvZHVjdHMgPSBmaW5kUHJvZHVjdHMoc2VsZWN0ZWRFbGVtZW50c1swXSxzZWxlY3RlZEVsZW1lbnRzWzFdKQogICAgaWYgKHR5cGVvZiBwcm9kdWN0cyAhPSAndW5kZWZpbmVkJykge3Byb2R1Y3RzLmZvckVhY2gocHJvZHVjdCA9PiB7ZWxlbWVudHNbcHJvZHVjdF0ub3duZWQgPSB0cnVlO30pfQogICAgc2VsZWN0ZWRFbGVtZW50cy5mb3JFYWNoKGtleSA9PiB7ZWxlbWVudHNba2V5XS5zZWxlY3RlZCA9IGZhbHNlO30pCiAgICBzZWxlY3RlZEVsZW1lbnRzID0gWycnLCcnXQogICAgcmVzdWx0RGlzcGxheS5pbm5lckhUTUwgPSBgJHt0eXBlb2YgcHJvZHVjdHMgPT0gJ3VuZGVmaW5lZCc/J05vIHByb2R1Y3QgZm91bmQgOignOmBDcmVhdGVkIDxzdHJvbmc+JHtwcm9kdWN0cy5qb2luKCcsICcpfTwvc3Ryb25nPiFgfWAKICAgIHVwZGF0ZVNlbGVjdGVkRGlzcGxheSgpCiAgICB1cGRhdGVFbGVtZW50cygpCiAgICB1cGRhdGVFbGVtZW50c0Rpc3BsYXkoKQogIH0KfQoKZnVuY3Rpb24gY2hhbmdlQ1NTKHZhcmlhYmxlLHZhbHVlKSB7ZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LnN0eWxlLnNldFByb3BlcnR5KCgiLS0iKS5jb25jYXQodmFyaWFibGUpLHZhbHVlKX0KdmFyIHRoZW1lID0gMApmdW5jdGlvbiBzd2l0Y2hUaGVtZSgpIHsKICB0aGVtZSA9ICh0aGVtZSsxKSUyCiAgY2hhbmdlQ1NTKCdiZycsWycjZmZmJywnIzAwMCddW3RoZW1lXSkKICBjaGFuZ2VDU1MoJ3RleHQnLFsnIzAwMCcsJyNmZmYnXVt0aGVtZV0pCn0KCmZ1bmN0aW9uIHNhdmUoKSB7CiAgbGV0IGdhbWVTYXZlID0ge30KICBPYmplY3Qua2V5cyhlbGVtZW50cykuZm9yRWFjaChrZXkgPT4ge2dhbWVTYXZlW2tleV0gPSBlbGVtZW50c1trZXldLm93bmVkfSkKICBsb2NhbFN0b3JhZ2Uuc2V0SXRlbSgiZ2FtZVNhdmUiLCBKU09OLnN0cmluZ2lmeShnYW1lU2F2ZSkpOwp9CgpmdW5jdGlvbiBsb2FkKCkgewogIGxldCBzYXZlZEdhbWUgPSBKU09OLnBhcnNlKGxvY2FsU3RvcmFnZS5nZXRJdGVtKCJnYW1lU2F2ZSIpKTsKICBpZiAoc2F2ZWRHYW1lKSB7CiAgICBPYmplY3Qua2V5cyhzYXZlZEdhbWUpLmZvckVhY2goa2V5ID0+IHsKICAgICAgaWYgKHR5cGVvZiBlbGVtZW50c1trZXldICE9ICd1bmRlZmluZWQnKSB7ZWxlbWVudHNba2V5XS5vd25lZCA9IHNhdmVkR2FtZVtrZXldfQogICAgfSkKICB9CiAgdXBkYXRlRWxlbWVudHMoKQogIHVwZGF0ZUVsZW1lbnRzRGlzcGxheSgpCn0KCmZldGNoRGF0YSgpCgogIA==`;
const _version = "V0.2"
if (btoa(document.body.querySelector("script").innerHTML) === _lastKnownHash) {
    save();

    let _usedHints = Number(localStorage.getItem("_hints")) ?? 0;

    const _elementsUnparsed = localStorage.getItem("gameSave");
    const _elements = JSON.parse(_elementsUnparsed);

    const _hackEls = [document.createElement("p"), document.createElement("button"), document.createElement("button"), document.createElement("button"), document.createElement("p"), document.createElement("p"),          document.createElement("br")];

    _hackEls[0].innerText = `Snail Elemental Hacks ${_version}:`;

    _hackEls[1].innerText = "Unlock all Elements";
    _hackEls[1].addEventListener("click", () => {
        _unlockAll();
    });

    _hackEls[2].innerText = "Reset collection";
    _hackEls[2].addEventListener("click", () => {
        _reset();
    });

    _hackEls[3].innerText = `Hint (${_usedHints} used)`;
    _hackEls[3].addEventListener("click", () => {
        _hackEls[4].innerText = _hint();
    });

    _hackEls[5].innerText = `Craftable Elements: Click to Refresh Craftable Elements!`;
    _hackEls[5].addEventListener("click", () => {
        _hackEls[5].innerText = `Craftable Elements:\n${_getCraftable().map(_el => _el.products.join(" and ")).join("\n")}`
    });

    _hackEls.forEach(_el => {
        document.body.append(document.createElement("br"), _el);
    });

    function _unlockAll() {
        Object.keys(_elements).forEach((_element) => {
            _elements[_element] = true;
        });

        localStorage.setItem("gameSave", JSON.stringify(_elements));

        load();
        window.scrollTo(0, document.body.scrollHeight);
    }

    function _reset() {
        Object.keys(_elements).forEach(_element => {
            _elements[_element] = false;
        });

        basicElements.forEach(_el => {
            _elements[_el] = true;
        });

        localStorage.setItem("gameSave", JSON.stringify(_elements));
        localStorage.setItem("_hints", 0);
        _usedHints = 0;
        _hackEls[3].innerText = `Hint (0 used)`;
        _hackEls[4].innerText = "";

        load();
    }

    function _getElBy(discovered = true) {
        const els = [];
        Object.keys(elements).forEach((el) => {
            if (elements[el].owned === discovered) {
                els.push(el);
            }
        });
        return els;
    }

    function _getCraftable() {
        const _undis = new Set(_getElBy(false));
        const _dis = new Set(_getElBy(true));

        const _craftable = formulae.filter((_el) => {
            if (_dis.has(_el.elements[0]) && _dis.has(_el.elements[1]) && _undis.has(_el.products[0])) {
                return _el;
            }
        });
        return _craftable;
    }

    function _hint() {
        const _els = _getCraftable();
        if (_els.length) {
            const _random = _els[Math.floor(Math.random() * _els.length)];

            const _string = _random["products"].join(" and ") + " = " + _random["elements"][0] + " + " + _random["elements"][1];

            ++_usedHints;
            localStorage.setItem("_hints", _usedHints);
            _hackEls[3].innerText = `Hint (${_usedHints} used)`;

            return _string;
        }
        else {
            return "You have discovered all elements!";
        }
    }
}
else {
    console.warn("Elemental Hacks refused to run, as they are outdated. Call the _showAdvanced function for details");
    function _showAdvanced() {
        console.log(`Elemental hacks ${_version}`);
        console.log(`=====================`);
        console.log(`Last known hash (version of Elemental): ${_lastKnownHash}`);
    }
}